const crypto = require('crypto')
const axios = require('axios')
const { newError, uuidv4, md5 } = require('../helpers/routerHelpers')
const dayjs = require('dayjs')
const Bank = require('../models/Bank')
const Error = require('../models/Error')
const imageToBase64 = require('image-to-base64')
const config = {
	publicKey:
		'-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAiEPragkOAc+PM2TqG1Xqh/+mqWP0dJge+VfJ/H75nwCchOMNG297SgRKx7M3\nrvwxUfTw602rZ1LiwLV+h16/tGj5BxuQCkfAj+QFp3P4A+Kar8spo1mW2i7MCshhtzF72SHJ\n9K1yH67RmrCZdHpYdezs5yb1FtccUkUUhpbTX9PBaKMhxmecJE1jORRiSCdRl+c54NHVAbxf\nGrDDMRFw3PFv9cCmLSvP8/7mI3ClmDz+e9PsxFDItaynaMogrJDOm3D4i3CF2YgVmGBNBWfy\na/0t88eCWfM34JJ87ufQuzi6Fs9n3XOeWXN8DNc02YD9/Ua7lKFxaFF9iQfZkB3ckwIDAQAB\n-----END RSA PUBLIC KEY-----',
	public:
		'-----BEGIN RSA PUBLIC KEY-----\r\nMIIBCgKCAQEAtJrooyqaW0uaHUrBcsolAr+O9RRu/BdUp1N2Rcb7b58w1TMGqMGM\r\n2dyHzIIEwsPP1XwYf5Qo3oTkDGB8HD4FgTQOHydponYirfoZ0kGLCitz8CPv2dzg\r\nimbScm3sBKLNjHL6Y5yiJ4um/Pz0XUWF1LuEeI4ChDxHDjok+trSW/PiWIFW0P6v\r\nqEWwch3Hpv75/f0zB1lmKxuwmjo08JwR+y596UdnU/n2ZwjgyJ53yoXqn6i9aKsh\r\naJiDHflgRndxmXRf5TfcZzpz33UltIb02PclNozw7lyROMr9IBqH4Vr06afZgmgs\r\nrbz0L3VEryLdNW6JUyf0ZH+KUhvL4bAmWQIDAQAB\r\n-----END RSA PUBLIC KEY-----\r\n',
	private:
		'-----BEGIN RSA PRIVATE KEY-----\r\nMIIEowIBAAKCAQEAtJrooyqaW0uaHUrBcsolAr+O9RRu/BdUp1N2Rcb7b58w1TMG\r\nqMGM2dyHzIIEwsPP1XwYf5Qo3oTkDGB8HD4FgTQOHydponYirfoZ0kGLCitz8CPv\r\n2dzgimbScm3sBKLNjHL6Y5yiJ4um/Pz0XUWF1LuEeI4ChDxHDjok+trSW/PiWIFW\r\n0P6vqEWwch3Hpv75/f0zB1lmKxuwmjo08JwR+y596UdnU/n2ZwjgyJ53yoXqn6i9\r\naKshaJiDHflgRndxmXRf5TfcZzpz33UltIb02PclNozw7lyROMr9IBqH4Vr06afZ\r\ngmgsrbz0L3VEryLdNW6JUyf0ZH+KUhvL4bAmWQIDAQABAoIBADqe7VPIyEFJ0MQh\r\nN5kis9CojKZP85YvnHKTTJhpdcNNUHRjE45DBIzSX+GpchIlrJgGp40BciKHz92U\r\nk7Q3DWJamxrRmB/7aFZAD5GHZLHwWLlhcMCuSNOjfDtYInt+vGkSCOO8O4XKdnE3\r\nSbncjwv1sZHPxlFVn1qm1Mn3rL/bZcnZBpHATp+pItXRK4wFZzUeqeXztdnsKH4o\r\nJQo79cp98J0JOxfbFzYvlo/1XuOpnlGykfrcNqt5ZCOmNt1/mb5eFPCZq16+sAMG\r\nsCErx+V0A0AR1oj6/KCzbz8cSNw7MnJQex/8sQl96UidoRBdZ16FK5luMf/tVWmN\r\nH9EjPAECgYEA2nksozuirpg2Iwy7L0eh9r2ap1uanYyd6NEGh9e8tIWnwbXWMixG\r\ne3J1kCe15mBbsf/251lHxKndsCE4Ag3KSUKeYCxKu72kIKa/oLs4mjxhpLhBzqfj\r\nYk9hp5Y3ouVkGft0nFkw1Rz8UUt8ir4ewpUoTTYe8jTWmvjYi0eVjokCgYEA06CS\r\nmjquH63cft7vPTtwzo7HpeYeJfCXXGjSNKBSamD5dbDFvLMhunuR6PGjKpQisBA7\r\nRnIwmyLbXtEdFu6PzWHQR15AEgX8+Jq8BzzxDIQtzah/bdGTNO7NXcms4i+duAMO\r\nlpi0+I/mDffRVDN3KHFVOn5ZdGSewvp+7XCSZVECgYAbdyZccw/VoT8VEvGpVPkQ\r\nmu+JYKPEcLwdW8HVbBLGIxNe7+w4rIZD2LTc5ZEhoDWG4CX7GadDGxPKo7J116P5\r\np81fS9ItXf73N99ZZpAMG9Eusxda0pJsdoxRVDo0WWBHP+x+B1xzPkyeL749dv9I\r\n+RVy933WdzwPiX83q00q+QKBgQCKfaJy28PnZ1fMjwfxAl0oT7fHkXhZS8FB8Dbf\r\nyaslgqC9rBk7C98eso8h6j/lNVwd7AFecIvuejklK6PlxejFdyVeDwfOw6xw5JH4\r\nCqGUl0uCMqpxq5yyHzS2E6zXuGF2ckmxs+16XHEo4uxSNfvcs44a4WSZDt/2qQc3\r\nS1wCgQKBgDNEcLbf6N6JUrfhqsQcXOV+2FM3pQ9MChaMCa4JWLjx5Bg68+eTXJ4x\r\nXr5CcJP5El6dy/Jm43Yq8b6VsKe+ttVwalvlY9/H9V8jgdsgd68hLWHrhX6axgHM\r\nFgVty49ujBslHahMLcJFNbEHaKiUMGXcnQakz9vcDkX2Fyz9YHBn\r\n-----END RSA PRIVATE KEY-----\r\n',
	key: '123456789012345678901234567890aa',
}

const statusError = {
	api: {
		'001': 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		222: 'Số tài khoản không hợp lệ',
		223: 'Số tài khoản không hợp lệ.',
		429: 'Tài khoản thấu chi không được phép ghi có tài khoản này theo quy định tại Hợp đồng tín dụng ký kết với MB. Quý khách vui lòng liên hệ CV QHKH để biết thêm chi tiết.',
		GW366: 'Hạn mức không hợp lệ',
		GW368: 'Hạn mức không hợp lệ',
		GW369: 'Hạn mức không hợp lệ',
		GW370: 'Số tiền giao dịch vượt quá số tiền cho phép',
		GW371: 'Không tìm thấy cấp phê duyệt tiếp theo',
		GW372: 'Tập tin tải lên thiếu thông tin',
		GW373: 'Cấu trúc dữ liệu không hợp lệ',
		GW375: 'Tài khoản chưa được cấu hình cho chuyển tiền theo lô',
		GW4000: '{{type}} thụ hưởng bị trùng trong danh sách tải lên {{accountNo}}',
		GW4001: 'Tên gợi nhớ không hợp lệ',
		GW4002: 'Số thự tự trong tệp tải lên không hợp lệ',
		GW4003: 'Vượt quá số lượng bản ghi tối đa {{max}}',
		GW4004: 'Tài khoản thụ hưởng không hợp lệ',
		GW4005: 'Tài khoản thụ hưởng trùng với danh sách tài khoản mặc định',
		GW4006: 'Bản ghi không đúng định dạng dòng {{line}}',
		GW4007: 'Quý khách vui lòng kiểm tra lại danh mục và tệp tin tải lên',
		GW711: 'Không thực hiện tạo được mã kiểm tra. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW712:
			'Hiện tại quý khách không thể tạo mã kiểm tra do đã tạo vượt quá số lần quy định. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW713: 'Mã kiểm tra hết hạn',
		GW714: 'Mã kiểm tra không chính xác',
		GW715: 'Mã kiểm tra không chính xác',
		GW521: 'Ngày cam kết bổ sung chứng từ không được vượt quá {{0}} ngày',
		GW716_note: 'Mã kiểm tra bị khoá trong {{second}} giây',
		GW716: 'Mã kiểm tra bị khoá do nhập sai quá nhiều lần. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW1106: 'Tài khoản thụ hưởng không được phép nhận tiền',
		'00': 'Thành công',
		'000': 'Thành công',
		100: 'Xác thực ESB thất bại',
		101: 'Quyền truy cập bị từ chối',
		202: 'Loại tiền tệ không hợp lệ',
		203: 'Dữ liệu không hợp lệ',
		204: 'Quốc tịch không hợp lệ.',
		205: 'Cấu trúc dữ liệu không hợp lệ.',
		206: 'Loại tệp tin không hợp lệ',
		207: 'Token không hợp lệ',
		208: 'Chi nhánh không hợp lệ',
		210: 'Charge code không hợp lệ',
		211: 'Tài khoản này bị khóa',
		212: 'Mã giao dịch đã được sử dụng',
		213: 'Mã kích hoạt không hợp lệ',
		214: 'Sản phầm này không hợp lệ',
		400: 'Tài khoản nguồn không đủ tiền để thực hiện giao dịch. Quý khách vui lòng bổ sung tiền trước khi duyệt lệnh.',
		401: 'Bản ghi đã tồn tại',
		402: 'Thiếu OTP',
		404: 'Bản ghi bị trùng lặp',
		405: 'Hệ thống đang bận',
		406: 'Hệ thống đang bận',
		407: 'Hoá đơn đã đóng không thể hoàn tiền.',
		408: 'Ngân hàng thụ hưởng tạm thời không hỗ trợ. Quý khách vui lòng thử lại trong giây lát.',
		409: 'PROMO_AIR_TICKET_CANT_BE_HOLD',
		412: 'Ngân hàng thụ hưởng không hỗ trợ dịch vụ',
		413: 'Mật khẩu cũ không chính xác',
		414: 'Dịch vụ tạm dừng hỗ trợ. Xin vui lòng quay lại sau',
		415: 'Tỷ giá không tồn tại',
		417: 'Tài khoản ngoại tệ trích tiền của Quý khách không đủ số dư để thực hiện giao dịch. Quý khách vui lòng bổ sung tiền trước khi duyệt lệnh hoặc tăng số ngoại tệ cần mua để đảm bảo giao dịch.',
		437: 'Tài khoản thấu chi đang bị tạm khóa do Khách hàng có nợ quá hạn hoặc lịch sử nợ quá hạn. Quý khách vui lòng liên hệ CV QHKH để biết thêm chi tiết.',
		501: 'TRANSACTION_MET_DEADLOCK',
		GW248: 'Tài khoản trả lãi và gốc không hợp lệ',
		GW249: 'Tài khoản nhận gốc không hợp lệ',
		GW293: 'Tên đăng nhập chỉ được bao gồm ký tự số và chữ',
		GW297: 'Thời gian hiệu lực không chính xác',
		GW343: 'Mã ngân hàng không hợp lệ. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW344: 'Đăng ký trực tuyến thất bại',
		GW345: 'Tài khoản thanh toán không tồn tại',
		GW346: 'Khách hàng chưa đăng ký phương thức xác thực',
		GW351: 'Tài khoản không tồn tại',
		GW352: 'Mã số khách hàng không tồn tại',
		GW355: 'Tạo Email không thành công',
		GW358: 'Danh mục  không hợp lệ',
		GW361: 'Tài khoản lương không hợp lệ',
		GW362: 'Khách hàng không thể đổi mật khẩu',
		OTD111: 'Tài khoản không đủ số dư để thực hiện giao dịch',
		GW631: 'Ngày bắt đầu và ngày kết thúc cách nhau tối đa 3 tháng',
		GW632: 'Reference number không tồn tại',
		GW633: 'Xuất file thất bại',
		GW634: 'Vui lòng tìm kiếm giao dịch trong khoảng thời gian 90 ngày liên tiếp',
		GW635: 'Vui lòng nhập khoảng ngày hoặc số tham chiếu',
		GW641: 'Số dư tài khoản không đủ để thực hiện giao dịch',
		GW705: 'Quý khách không có quyền tải về hoá đơn này.',
		OTD109: 'Tài khoản trả lãi, trả gốc không hợp lệ',
		CGW123: 'Thẻ không ở trạng thái sẵn sàng hoạt động',
		internet: {
			card: 'Nhập OTP sai',
		},
		OTD002: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		OTD300: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		OTD301: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		upi_map_4: 'Cập nhật trạng thái thẻ không thành công, vui lòng thử lại sau',
		410: 'Mã xác thực không chính xác. Bạn vui lòng thử lại!',
		GW298: 'Tài khoản thụ hưởng đã tồn tại.',
		TimeoutError: 'Kết nối vượt quá thời gian quy định.',
		E050: 'Khách hàng đã được đăng ký trước đó',
		E084: 'Địa chỉ email đã được đăng ký trước đó. Quý khách vui lòng kiểm tra lại',
		201: 'Số tài khoản không hợp lệ.',
		209: 'Số tiền không hợp lệ',
		GW363: 'Khách hàng không hợp lệ',
		200: 'Mã khách hàng không hợp lệ.',
		E049: 'Mã khách hàng không hợp lệ. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E073: 'Mã khách hàng không hợp lệ. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E003: 'Thông tin đăng nhập không hợp lệ. Quý khách vui lòng kiểm tra lại',
		E058: 'Mã OTP không hợp lệ. Quý khách vui lòng kiểm tra lại',
		E086: 'Mật khẩu không hợp lệ',
		GW200: 'Phiên giao dịch không hợp lệ. Vui lòng đăng nhập lại',
		OTD105: 'Không đúng kỳ hạn',
		GW289: 'IP không cho phép kết nối',
		GW359:
			'Quý khách vui lòng thực hiện Giao dịch trong khoảng thời gian 08:00 đến 17:30 từ thứ 2 đến thứ sáu, 08:00 đến 12:00 thứ Bảy không bao gồm ngày nghỉ, ngày lễ',
		E012: 'Số điểm không đủ để thanh toán. Quý khách vui lòng kiểm tra lại',
		225: 'Hệ thống không hỗ trợ xem chi tiết với loại giao dịch này.',
		GW360: 'Ứng dụng đang trong quá trình xây dựng, quý khách vui lòng đăng nhập lại sau khi có thông báo triển khai chính thức',
		E005: 'Hệ thống Quản lý điểm đang tạm dừng để bảo trì, Quý khách vui lòng quay lại sau ít phút',
		E010: 'Hệ thống Quản lý điểm đang tạm dừng để bảo trì, Quý khách vui lòng quay lại sau ít phút',
		E001: 'Hệ thống Quản lý điểm đang tạm dừng để bảo trì, Quý khách vui lòng quay lại sau ít phút',
		002: 'Hệ thống tạm thời gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		301: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		300: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		500: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		504: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		HttpErrorResponse: 'Hệ thống tạm thời bị gián đoạn. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW357: 'Giao dịch này đang chờ phê duyệt',
		421: 'Giao dịch không thành công',
		411: 'Giao dịch quá hạn mức',
		403: 'Quý khách đã nhập sai OTP quá số lần cho phép, vui lòng thử lại giao dịch sau ít phút.',
		E035: 'Vinid  của Quý khách đã bị khóa. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E103: 'VinID của Quý khách đã bị khóa. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E077: 'VinID của Quý khách đã hết hạn. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E036: 'VinID của Quý khách chưa kích hoạt. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E105: 'VinID của Quý khách chưa kích hoạt. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		416: 'Tài khoản thu phí không đủ tiền để thực hiện giao dịch. Quý khách vui lòng bổ sung tiền trước khi duyệt lệnh.',
		GW500: 'Tính phí không thành công',
		GW501: 'Tính tỉ giá không thành công',
		GW503: 'Giao dịch mua ngoại tệ không thành công. Quý khách vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW502: 'Lấy thông tin RM không thành công',
		GW504: 'Quá hạn mức chuyển tiền',
		GW505: 'Quá hạn mức mua ngoại tệ',
		GW506: 'Có lỗi xảy ra trong quá trình xác định trạng thái giao dịch',
		GW507: 'Các file chứng từ đang trong quá trình ký duyệt',
		GW509: 'Giao dịch đã thực hiện hạch toán, đề nghị Khách hàng liên hệ Chi nhánh/PGD gần nhất hoặc RM quản lý để thực hiện HỦY',
		GW508: 'Trạng thái Hủy không hợp lệ.',
		GW510: 'Có lỗi xảy ra trong quá trình tạo file chứng từ gốc',
		GW511: 'Không được quyền xác nhận mua ngoại tệ của giao dịch này',
		GW512: 'Tên ngân hàng vượt quá độ dài cho phép',
		GW513: 'Địa chỉ ngân hàng vượt quá độ dài cho phép',
		GW514: 'Chi tiết thanh toán vượt quá độ dài cho phép',
		GW515: 'Giao dịch này đã được bổ sung chứng từ nợ. Vui lòng kiểm tra  giao dịch bổ sung trong danh sách chờ phê duyệt',
		GW516: 'Dữ liệu của giao dịch đã hết hạn hoặc không hợp lệ tại thời điểm hiện tại. Quý khách vui lòng tạo giao dịch mới.',
		GW517: 'Giao dịch đã thực hiện hạch toán, đề nghị Khách hàng liên hệ Chi nhánh/PGD gần nhất hoặc RM quản lý để thực hiện HỦY.',
		GW519: 'Tài khoản nguồn VND không đủ tiền để thực hiện giao dịch. Quý khách vui lòng bổ sung tiền trước khi duyệt lệnh.',
		GW651: 'Loại giao dịch không đúng',
		GW652: 'Hệ thống đang xử lý, quý khách vui lòng thử lại sau',
		GW653: 'Không tìm thấy giao dịch với số tham chiếu này',
		GW654: 'Người dùng không hợp lệ',
		GW655: 'Loại giao dịch không hợp lệ',
		GW900: 'Lấy thông tin thuế cần nộp bị lỗi',
		GW901: 'Mã số thuế không tồn tại trong danh mục',
		GW902: 'Nội dung thanh toán thuế của Quý khách vượt quá 200 ký tự cho phép của hệ thống, Quý khách vui lòng chọn lại món thuế cần thanh toán',
		GW903: 'Kỳ thuế không đúng định dạng',
		GW904: 'Vui lòng chọn thông tin nghĩa vụ thuế cần nộp',
		GW905: 'Số tiền nộp ngân sách mỗi giao dịch phải > 0',
		GW906: 'Cơ quan thu không thuộc KBNN. Vui lòng lựa chọn thông tin phù hợp',
		GW907: 'Vui lòng nhập đầy đủ thông tin',
		GW908: 'Tài khoản nguồn không hợp lệ',
		GW909: 'Quý khách vui lòng chỉ chọn 1 nghĩa vụ thuế',
		GW800: 'Không tìm thấy thông tin hóa đơn',
		GW801: 'Xóa thông tin hóa đơn không thành công',
		GW802: 'Mã hóa đơn đã tồn tại',
		GW1100: 'Mã ngân hàng không hợp lệ',
		GW1103: 'Quý khách đã vượt quá {{maxTrans}} bản ghi/ngày',
		GW1104: 'Tên tập tin đã sử dụng trong giao dịch khác. Quý khách vui lòng đổi tên tập tin hoặc sử dụng tập tin khác.',
		GW1105: 'Quý khách không được phân quyền thực hiện chức năng này.',
		GW2531: 'Giao dịch này đã được gửi và đang chờ phê duyệt',
		234: 'Hệ thống BPM không yêu cầu khách hàng bổ sung hồ sơ',
		PKI001: 'Chuỗi chứng thư của bạn không chính xác.',
		PKI002: 'Chữ ký số của bạn không hợp lệ. Bạn vui lòng kiểm tra lại.',
		PKI003: 'Ngày ký của bạn không hợp lệ. Bạn vui lòng kiểm tra lại.',
		PKI004: 'Chữ ký số của bạn đã hết hiệu lực. Bạn vui lòng kiểm tra lại.',
		PKI005: 'Chữ ký số của bạn đã bị thu hồi. Bạn vui lòng kiểm tra lại.',
		PKI006: 'Chữ ký số của bạn không hợp lệ. Bạn vui lòng kiểm tra lại.',
		PKI007: 'Xác thực chữ ký số không thành công.',
		PKI008: 'Không tìm thấy chữ ký. Bạn vui lòng kiểm tra lại.',
		PKI009: 'Không tìm thấy tập tin để thực hiện ký. Bạn vui lòng kiểm tra lại.',
		PKI010: 'Định dạng của tập tin bạn ký không được hỗ trợ. Bạn vui lòng kiểm tra lại.',
		PKI011: 'Dữ liệu thực hiện ký số không hợp lệ. Bạn vui lòng kiểm tra lại.',
		PKI012: 'Mã của thiết bị chữ ký số không hợp lệ. Bạn vui lòng kiểm tra lại.',
		GW1001: 'Không tìm thấy thông tin khách hàng',
		GW1019: 'Mã hóa đơn không hợp lệ( Mã hóa đơn đã được thanh toán hoặc mã hóa đơn đã hết hạn thanh toán)',
		GW1020: 'Mã hoá đơn không tồn tại',
		GW1021: 'Mã hóa đơn đã được thanh toán',
		GW1068: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ',
		GW1096: 'Lỗi hệ thống',
		GW1042: 'Giao dịch không thành công',
		GW2741: 'Quý khách vui lòng truy cập lại hệ thống BizMB vào giờ làm việc ngày hôm sau để duyệt giao dịch do đã quá giờ cut-off-time của hệ thống',
		GW2742: 'Quý khách vui lòng truy cập lại hệ thống BizMB vào giờ làm việc ngày hôm sau để duyệt giao dịch do đã quá giờ cut-off-time của hệ thống',
		GW1002: 'Giao dịch bị từ chối',
		GW1003: 'Mã hóa đơn đã hết hạn',
		GW1004: 'Mệnh giá không hợp lệ',
		GW1005: 'Tài khoản không đủ số dư',
		GW1006: 'Mã hóa đơn không hợp lệ( Mã hóa đơn đã được thanh toán hoặc mã hóa đơn đã hết hạn thanh toán)',
		GW1007: 'Mã hoá đơn không tồn tại',
		GW1008: 'Mã hóa đơn đã được thanh toán',
		GW1009: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ',
		GW1010: 'Lỗi hệ thống',
		GW1011: 'Không xác định được kết quả giao dịch. Liên hệ với ngân hàng thụ hưởng để xác nhận kết quả',
		GW1012: 'Lỗi trong việc xử lý giao dịch',
		GW1013: 'Hệ thống Ngân hàng ngoài lỗi, hệ thống tự động block để tránh ảnh hưởng đến các giao dịch khác',
		GW1014: 'Hệ thống quá tải',
		GW1015: 'Tham số truyền vào bị thiếu',
		GW1016: 'Loại tiền giao dịch không hợp lệ',
		GW1017: 'Giao dịch bị trùng lặp',
		GW3731: 'Số lượng bản ghi tối đa phải là 10000',
		GW1200: 'Lô đã được phê duyệt. Không thể thực hiện phê duyệt từng phần',
		GW1201: 'Không thể thực hiện phê duyệt từng phần',
		GW1202: 'Không thể thực hiện phê duyệt từng phần',
		GW1203: 'Không thể tìm thấy giao dịch trong lô',
		GW1204: 'Số giao dịch tối thiểu được phê duyệt phải từ {{minTransaction}} giao dịch trở lên',
		GW1205: 'Số giao dịch chờ phê duyệt còn lại phải từ {{minTransaction}} giao dịch trở lên',
		GW1206: 'Không thể lấy thông tin giao dịch được phê duyệt từng phần',
		GW1111: 'Doanh nghiệp đã tồn tại giao dịch mở tài khoản số đẹp đang chờ phê duyệt.',
		GW1112: 'Tài khoản số đẹp đã được sử dụng. Quý khách vui lòng chọn số tài khoản khác.',
		GW1300: 'Không tìm thấy Ngân hàng thụ hưởng.',
		4: 'Giao dịch thất bại. Vui lòng liên hệ hotline 1900545426 để biết thêm chi tiết.',
		102: 'Số hợp đồng không chính xác',
		103: 'Quý khách vui lòng nộp đủ phí bảo hiểm định kì để đủ điều kiện nộp phí đóng thêm (top-up)',
		104: 'Quý khách vui lòng nộp đủ phí bảo hiểm định kì để đủ điều kiện nộp phí đóng thêm (top-up)',
		1004: 'Lỗi phân tích dữ liệu. Bạn vui lòng thử lại sau.',
		2201: 'Tham số ',
		2304: 'Đã tồn tại khoản vay thấu chi.',
		2305: 'Thẻ không hợp lệ không phải card MAIN',
		2306: 'Trạng thái thẻ không hợp lệ',
		2307: 'Thẻ chưa active',
		2308: 'Thẻ hết hạn',
		2310: 'Vui lòng nhập đúng thông tin thẻ của bạn. Trân trọng',
		2311: 'Ngày active thẻ không hợp lệ',
		2312: 'Điều kiện thẻ không hợp lệ',
		2313: 'Ngày sinh không hợp lệ',
		4002: 'Quý khách không có khoản vay chờ giải ngân tại Mcredit, vui lòng liên hệ hotline của Mcredit  1900636769 hoặc đến trực tiếp các quầy giao dịch của MB để được hỗ trợ',
		4203: 'Bạn không thuộc đối tượng cấp tín dụng tại MB. Trân trọng!',
		4205: 'Cấu hình không hợp lệ',
		4208: 'Customer limit invalid',
		4209: 'Quý khách chưa đủ điều kiện vay tiêu dùng CBNV MB do tồn tại khoản vay còn hạn',
		4210: 'Không tìm thấy thông tin khách hàng trong danh sách khách hàng tiềm năng',
		4212: 'Không tìm thấy key lãi suất ',
		4213: 'Quý khách chưa đủ điều kiện vay tiêu dùng CBNV MB theo quy định sản phẩm',
		4214: 'Quý khách chưa đủ điều kiện vay do đang trong thời gian bị kỷ luật',
		4215: 'Quý khách chưa đủ điều kiện vay do thời gian công tác còn lại trước nghỉ hưu dưới 1 năm',
		4216: 'Quý khách chưa đủ điều kiện vay do thời gian công tác dưới 1 năm',
		4217: 'Quý khách chưa đủ điều kiện vay do không tìm thấy thông tin trên Hris',
		4218: 'Giao dịch vay vốn của bạn chưa thành công do có nợ quá hạn tại MB. Trân trọng cảm ơn!',
		4219: 'Độ tuổi của bạn không thuộc đối tượng cấp tín dụng tại MB. Trân trọng!',
		4220: 'Bạn vui lòng đến điểm giao dịch gần nhất của MB để thực hiện cập nhật đăng ký dịch vụ MB điện tử theo mẫu biểu mới. Trân trọng cám ơn!',
		4221: 'Quý khách chưa đủ điều kiện vay do có có khoản vay tín chấp khác theo quy định SP.',
		4222: 'Quốc tịch của bạn không thuộc đối tượng cấp tín dụng tại MB. Trân trọng!',
		GW01: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW02: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW22: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW247: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW342: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW348: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		MBOT1: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW367: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW374: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW377: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW378: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW379: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW380: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW381: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW382: 'Số tiền đề nghị vay vượt quá hạn mức còn lại của thẻ.',
		GW383: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW384: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW385: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW389: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW391: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW392: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW396: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW397: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW399: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW401: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW402: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW403: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW404: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW405: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW407: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW408: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW409: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW410: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW411: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW412: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW413: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW414: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW415: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW417: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW418: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW421: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW422: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW423: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW424: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW425: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW427: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW429: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW430: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW431: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW432: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW433: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW434: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW439: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW442: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW443: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW444: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW445: 'Không truy vấn được thông tin thẻ/tài khoản thụ hưởng',
		GW446: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW447: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW449: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW451: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW454: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW455: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW459: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW461: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW462: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW463: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW464: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW465: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 :để biết thêm chi tiết.',
		GW466: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW467: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW468: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW469: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW471: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW472: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW473: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW474: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW475: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW476: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW477: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426để biết thêm chi tiết.',
		GW480: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW481: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW485: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW489: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW490: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW491: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW493: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW495: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW498: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW499: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		GW520: 'Quý khách không thể thực hiện bán trái phiếu trong thời gian chốt danh sách trả lãi',
		GW545: 'Thẻ ghi nợ tự động đã được đăng ký',
		GW546: 'Id thẻ chưa được đăng kí trích nợ',
		C001: 'Thông tin khách hàng không hợp lệ. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E004: 'Hết thời gian giao dịch. Bạn vui lòng đăng nhập lại để sử dụng dich vụ',
		E025: 'Số thẻ VinID không hợp lệ. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E042: 'Thông tin ngày tháng không chính xác. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E057: 'Giao dịch không thành công. Quý khách vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E065: 'Thông tin tài khoản không hợp lệ. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E078: 'Định dạng email không hợp lệ. Bạn vui lòng kiểm tra lại hoặc liên hệ MB247 1900545426 để được trợ giúp',
		E087: 'Số Mobile đã được đăng ký trước đó. Bạn vui lòng kiểm tra lại',
		E095: 'Mã hóa đơn không tồn tại. Bạn vui lòng kiểm tra ',
		E098: 'Giao dịch của bạn đã được hủy trước đó',
		E102: 'Địa chi email không được phép thay đổi. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		E200: 'Mã cửa hàng VinID không hợp lệ',
		E203: 'Lỗi hệ thống VINID.  Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		ES001: 'Không thể kết nối tới máy chủ.',
		ES002: 'Quá thời gian chờ phản hồi.',
		ES201: 'Số tài khoản không hợp lệ.',
		ES202: 'Tiền tệ không khả dụng.',
		ES203: 'Thông tin đầu vào không hợp lệ.',
		ES207: 'Mã token không hợp lệ.',
		ES208: 'Chi nhánh không hợp lệ.',
		ES209: 'Số tiền không khả dụng.',
		ES211: 'Tài khoản đã bị khóa.',
		ES212: 'Giao dịch đã được sử dụng.',
		ES235: 'Nhà cung cấp không khả dụng.',
		ES300: 'Dữ liệu đầu ra sai định dạng.',
		ES400: 'Số dư tài khoản không đủ.',
		ES401: 'Hóa đơn đã được thanh toán.',
		ES404: 'Trùng đúp bản ghi.',
		ES411: 'Giao dịch đã tới giới hạn.',
		ES412: 'Ngân hàng thụ hưởng chưa tham gia dịch vụ.',
		ES421: 'Giao dịch chưa hoàn thành.',
		ES429: 'Chuyển tiền thất bại.',
		ES437: 'Tài khoản thấu chi đã bị đóng.',
		ES443: 'Thực hiện thanh toán thất bại.',
		ES500: 'Hệ thống tạm thời gián đoạn, vui lòng thử lại sau.',
		G999: 'Thông tin khách hàng không hợp lệ. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		'GW-1': 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW100: 'Thông tin đầu vào không hợp lệ',
		GW102: 'Loại tài khoản không hợp lệ',
		GW14: 'Số thẻ của bạn không hợp lệ',
		GW16: 'Số dư tài khoản của bạn không đủ',
		GW17: 'Thông tin đăng nhập không hợp lệ',
		GW18: 'Khách hàng đang bị khóa',
		GW19: 'Khách hàng không bị khóa',
		GW20: 'Bạn chưa đăng ký dịch vụ, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ..',
		GW295: 'Tên đăng nhập có độ dài tối đa 30 ký tự',
		GW21: 'Thông tin đăng nhập không hợp lệ',
		GW221: 'Tên tài khoản thụ hưởng không chính xác',
		GW25: 'Tài khoản của bạn đã được kích hoạt trước đây.',
		GW250: 'Kỳ hạn tiết kiệm không hợp lệ',
		GW251: 'Số tiền tiết kiệm tối thiểu là 1.000.000 đồng',
		GW252: 'Số tiền tiết kiệm vượt quá số dư tài khoản thanh toán',
		GW253: 'Bạn không có tài khoản tiết kiệm nào',
		GW254: 'Ngân hàng thụ hưởng không hợp lệ',
		GW255: 'Loại tiền tệ không hợp lệ',
		GW211: 'Lỗi liên kết nguồn thẻ',
		CGW100: 'Có lỗi trong quá trình xử lý dữ liệu',
		GW256: 'Gói dịch vụ của bạn chưa được hỗ trợ giao dịch này. Bạn vui lòng đến điểm giao dịch gần nhất của MB để nâng cấp gói dịch vụ',
		GW257: 'Không thể truy vấn được thông tin phí của giao dịch',
		GW258: 'Xác thực giao dịch thất bại',
		GW259: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW26: 'Bạn chưa được kích hoạt dịch vụ',
		GW260: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW261: 'Không thể hoàn tiền lại cho bạn',
		GW262: 'Thẻ của bạn đã tồn tại trên hệ thống',
		GW263: 'Bạn đã có CIF trên hệ thống',
		GW264: 'Tên đăng nhập đã được sử dụng, bạn vui lòng dùng tên đăng nhập khác',
		GW265:
			' Thẻ đang ở trạng thái không được phép mở khóa qua kênh online, Qúy khách vui lòng đến quầy giao dịch của MB hoặc liên hệ 1900545426 để được hỗ trợ',
		GW266: 'Thiết bị của bạn chưa được kích hoạt, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW267: 'Thiết bị của bạn không tồn tại.  Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW268: 'Không tìm thấy danh sách thiết bị đăng ký của bạn, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW269: 'Bạn đã đăng ký tối đa số thiết bị được cho phép, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW270: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW271: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW272: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW273: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW274: 'Phiên giao dịch trong ngày đã hết. Tiếp tục giao dịch người thụ hưởng sẽ nhận tiền vào ngày làm việc tiếp theo',
		GW275: 'Số thẻ không tồn tại. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW276: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW277: 'Thẻ không thuộc quyền sở hữu của bạn, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW278: 'Tài khoản không thuộc quyền sở hữu của bạn, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ .',
		GW279: 'Mã kích hoạt không chính xác. Vui lòng thử lại.',
		GW280: 'Sản phẩm không hợp lệ',
		GW281: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW282: 'Kích hoạt tài khoản thất bại. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW283: 'Mã captcha không chính xác. Vui lòng thử lại.',
		GW284: 'Bạn đã đăng ký trước đó, vui lòng sử dụng thông tin đã đăng ký',
		GW285: 'Thông tin đăng ký đã được sử dụng',
		GW286: 'Thông tin đăng ký đã được sử dụng',
		GW287: 'Email không khớp với đăng ký tại MB. Bạn vui lòng kiểm tra lạ.',
		GW288: 'Số điện thoại không khớp với đăng ký tại MB. Bạn vui lòng kiểm tra lại.',
		GW290:
			' Địa chỉ email không đúng với đăng ký trên hệ thống MB trước đó. Bạn vui lòng kiểm tra lại hoặc đến điểm giao dịch MB gần nhất để cập nhật lại email.',
		GW291:
			' Số điện thoại không đúng với đăng ký trên hệ thống MB trước đó. Bạn vui lòng kiểm tra lại hoặc đến điểm giao dịch MB gần nhất để cập nhật lại số điện thoại.',
		GW292: 'Không tồn tại service code',
		GW294: 'Tên đăng nhập có độ dài tối thiểu 3 ký tự',
		GW296: 'Vui lòng nhập mã xác thực (OTP)',
		GW299: 'Số tiền chuyển khoản vượt quá hạn mức, vui lòng kiểm tra lại.',
		GW30: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW300: 'Tài khoản/thẻ của bạn đang trong quá trình đồng bộ, quý khách vui lòng đăng nhập lại ứng dụng để thực hiện giao dịch',
		GW301: 'Tài khoản chưa được kích hoạt',
		GW302: 'Tài khoản không cho phép thực hiện gửi tiền đi',
		GW303: 'Tài khoản không cho phép nhận tiền về',
		GW304: 'Tài khoản không cho phép truy vấn thông tin',
		GW32: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		GW320: 'Thẻ của bạn đã bị đóng, vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ..',
		GW330: 'Định dạng dữ liệu không hợp lệ',
		GW331: 'Ngày bắt đầu phải nhỏ hơn ngày kết thúc',
		GW332: 'Vui lòng truy vấn giao dịch trong khoảng thời gian 3 tháng gần nhất',
		GW333: 'Ngày truy vấn không được vượt quá ngày hiện tại',
		GW334: 'Mật khẩu mới chứa tên đăng nhập',
		GW335: 'Mật khẩu mới quá ngắn',
		GW336: 'Mật khẩu mới quá dài',
		GW337: 'Mật khẩu mới phải chứa ký tự viết hoa',
		GW338: 'Mật khẩu mới phải chứa ký tự viết thường',
		GW339: 'Mật khẩu mới phải chứa chữ và số',
		GW340: 'Mật khẩu mới phải chứa ký tự đặc biệt',
		GW341: 'Bạn đã sử dụng mật khẩu này gần đây. Vui lòng chọn một mật khẩu khác',
		GW347: 'Bạn vui lòng chọn tài khoản nhận khác với tài khoản nguồn',
		GW349: 'Số CMTND/Hộ chiếu không khớp với đăng ký tại MB. Bạn vui lòng kiểm tra lại.',
		GW350: 'Không tìm thấy tài khoản thụ hưởng tương ứng',
		GW353: 'Số tài khoản/thẻ không tồn tại. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		GW354: 'Tài khoản nhận khác đơn vị tiền tệ ',
		GW356: 'Mật khẩu hiện tại không đúng',
		GW364: 'Quý khách không đủ điều kiện vay thấu chi',
		GW365: 'Thông tin địa chỉ email chưa hợp lệ. Quý khách vui lòng thực hiện cập nhật địa chỉ email. Trân trọng cảm ơn!',
		GW376: 'Bạn vui lòng không sử dụng tài khoản lương để chuyển khoản ra ngoài MB',
		GW38: 'Số tiền vượt quá hạn mức tối đa trên 1 giao dịch',
		GW386: 'Vượt hạn mức rút trong tháng',
		GW387: 'Thời gian kích hoạt chưa đủ một tháng',
		GW112: 'Mật khẩu mới không khớp!',
		topup_updating: 'Thông tin hợp đồng đang cập nhật. Quý khách vui lòng liên hệ  hotline 02422298888 để được hỗ trợ',
		topup_only: 'Phí TOPUP chỉ hỗ trợ HĐBH Kiến Tạo Ước Mơ',
		topup_only_support: 'Hợp đồng không đủ điều kiện. Phí Top-up chỉ hỗ trợ HĐBH Kiến Tạo Ước Mơ',
		have_due: 'HĐBH có nợ phí bảo hiểm',
		topup_lapse: 'Hợp đồng bảo hiểm đã mất hiệu lực. Quý khách vui lòng liên hệ  hotline 02422298888 để được hỗ trợ ',
		topup_reversed: 'Hợp đồng bảo hiểm đã hủy. Quý khách vui lòng liên hệ  hotline 02422298888 để được hỗ trợ',
		mbal_topup_err: 'Hợp đồng không đủ điều kiện thanh toán. Quý khách vui lòng liên hệ hotline MB Ageas Life 02422298888 để được hỗ trợ',
		GW388: 'Nhóm vay không hợp lệ',
		GW390: 'Loại thẻ không hợp lệ',
		GW393: 'Bạn đang có phát sinh nợ quá hạn tại MB. Vui lòng liên hệ hotline 1900545426 để được hỗ trợ',
		GW394: 'Bạn đã mở khoản vay trước đó',
		GW395: 'Bạn có hồ sơ đang xử lý, đề nghị không khởi tạo tiếp khoản vay. Trân trọng!',
		GW398: 'Bạn chưa đủ điều kiện vay vốn theo quy định của sản phẩm',
		GW40: 'Số tiền không hợp lệ',
		GW400: 'Giao dịch vay vốn của Bạn chưa thành công do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		GW406: 'Bạn vui lòng đến điểm giao dịch gần nhất của MB để thực hiện cập nhật đăng ký dịch vụ MB điện tử theo mẫu biểu mới.Trân trọng cảm ơn!',
		GW416:
			' Tài khoản nhận tiền giải ngân không hợp lệ, bạn vui lòng liên hệ hotline của Mcredit  1900636769 hoặc đến trực tiếp các quầy giao dịch của MB để được hỗ trợ',
		GW419: 'Ảnh chụp không đủ tiêu chuẩn để nhận diện, vui lòng thực hiện lại theo hướng dẫn trên màn hình.',
		GW420: 'Thông tin trên ảnh không trùng với thông tin bạn cung cấp, vui lòng kiểm tra lại',
		GW426: 'Đã xẩy ra lỗi đổi quà! Xin hãy liên lạc với hotline MBBank 1900545426 để được hỗ trợ.',
		GW428: 'Để trải nghiệm sản phẩm bạn vui lòng đến điểm giao dịch gần nhất của MB để đăng ký/nâng cấp gói dịch vụ eMB',
		GW435: 'Mã giảm giá không hợp lệ',
		GW436: 'Thời gian áp dụng mã giảm giá đã hết',
		GW437: 'Loại vé bạn vừa lựa chọn đã hết, vui lòng chọn loại vé khác.',
		GW438: 'Phiên mua vé đã hết hạn, vui lòng thực hiện lại',
		GW440: 'Vui lòng kiểm tra lại thời gian bán vé',
		GW441: 'Mã giảm giá đã sử dụng hết',
		GW448: 'Bạn không đủ điều kiện để đăng ký tài khoản chứng khoán MBS. Vui lòng ra quầy để hoàn thiện hồ sơ và nâng cấp gói dịch vụ.',
		GW45: 'Bạn đã hủy dịch vụ',
		GW450: 'Mã khách hàng không tồn tại',
		GW452: 'Đăng ký thanh toán tự động không thành công',
		CGW206: 'Không lấy được thông tin thẻ',
		CGW207: 'Thẻ không tồn tại hoặc chưa được xuất kho trong CardPortal',
		GW458: 'Hóa đơn đã được đăng ký tự động, bạn có muốn chỉnh sửa không?',
		GW453: 'Chưa hỗ trợ thanh toán tự động cho nhà cung cấp này',
		GW456:
			'Hợp đồng của quý khách đang ở trạng thái không hoạt động.Quý khách vui lòng ra quầy để thay đổi trạng thái hợp đồng hoặc gọi lên MB 247 Hotline 1900545426 để được hỗ trợ.Trân trọng cảm ơn!',
		GW457: 'Giá trị đề xuất lớn hơn hạn mức hiện tại',
		GW460: 'Mã khách hàng đã được đăng ký thanh toán tự động bởi khách hàng khác',
		GW470: 'Để đảm bảo có đủ thông tin đăng ký thu tự động, bạn vui lòng thực hiện đăng ký khi hóa đơn vẫn còn nợ',
		GW478: 'Khoản vay của Quý khách không được thực hiện. Vui lòng liên hệ MB247 1900545426 để được trợ giúp',
		GW479:
			' Quý khách đã đăng ký khoản vay thành công! Hệ thống sẽ xử lý trong vòng 24h. Quý khách vui lòng kiểm tra Email để nhận kết quả xử lý từ MBBANK!',
		GW482: 'Số lượng trái phiếu không hợp lệ',
		GW483: 'Ngày mua không được rơi vào 5 ngày làm việc trước ngày trả lãi',
		GW484: 'Bạn vui lòng đến điểm giao dịch gần nhất của MB để thực hiện cập nhật đăng ký dịch vụ MB điện tử theo mẫu biểu mới.Trân trọng cảm ơn!',
		GW486: 'Quý khách có hồ sơ đang xử lý, đề nghị không khởi tạo tiếp khoản vay. Trân trọng!',
		GW487:
			' Ngày giao dịch rơi vào ngày nghỉ, hợp đồng mua bán TPDN sẽ có hiệu lực kể từ ngày làm việc tiếp theo. QK có đồng ý tiếp tục thực hiện giao dịch? ',
		GW488: 'Khách hàng không thuộc đối tượng được mua TPDN online',
		GW492: 'Tài khoản chưa được liên kết.',
		GW494: 'Quý khách vui lòng tới chi nhánh/phòng giao dịch để thực hiện bán trước ngày dự kiến chuyển nhượng',
		GW496: 'Tạm thời TPDN chưa hỗ trợ bán vào ngày nghỉ, QK vui lòng thực hiện vào ngày làm việc tiếp theo. Trân trọng!',
		GW497: 'Thông tin truy vấn không hợp lệ, quý khách vui lòng liên hệ hotline 1900545426 để được hỗ trợ',
		GW52: 'Tổng số tiền vượt quá hạn mức tối đa trong ngày',
		GW53: 'Vượt quá số lượng giao dịch tối đa trong ngày',
		GW54: 'Số tiền nhỏ hơn hạn mức tối thiểu trên 1 giao dịch',
		GW640: 'Vượt quá số lượng giao dịch tối đa',
		GW55: 'Vượt quá hạn mức giao dịch trong tháng',
		GW59: 'Bạn đã bị khóa dịch vụ do nhập sai mật khẩu quá số lần cho phép',
		GW71: 'Nội dung giao dịch có ký tự đặc biệt',
		GW80: 'Số thẻ không hợp lệ',
		GW84: 'Tài khoản thụ hưởng không hợp lệ',
		GW89: 'Hạn mức chuyển tiền của quý khách chưa được thiết lập, vui lòng kiểm tra lại. Chi tiết liên hệ MB 24/7 theo số 1900 545426 để được hỗ trợ',
		GW99: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		GW999: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		GW525: 'Dịch vụ này đã được nâng cấp, bạn vui lòng cập nhật app để tiếp tục sử dụng dịch vụ',
		GW529:
			'Bạn đã để hết thời gian đăng ký Digital OTP trên App, vui lòng đến quầy giao dịch MBBank gần nhất hoặc liên hệ hotline 1900545426 để được hỗ trợ',
		GW551: 'Số điện thoại không đăng ký dịch vụ chuyển tiền qua số điện thoại',
		GW556:
			'Quý khách đang sử dụng dịch vụ tại MB bằng Hộ chiếu. Vui lòng mang theo Chứng minh nhân dân/Căn cước công dân kèm Hộ chiếu của Quý khách ra quầy MB gần nhất để cập nhật thông tin và tiếp tục sử dụng sản phẩm dịch vụ tại Mcredit. Trân trọng cảm ơn!',
		GW557:
			'Quý khách đang sử dụng dịch vụ tại MB bằng Chứng minh thư Quân đội. Vui lòng mang theo Chứng minh nhân dân/Căn cước công dân kèm Chứng minh thư Quân đội của Quý khách ra quầy MB gần nhất để cập nhật thông tin và tiếp tục sử dụng sản phẩm dịch vụ tại Mcredit. Trân trọng cảm ơn!',
		NP01: 'Tài khoản thụ hưởng hoặc tài khoản của thẻ thụ hưởng không hợp lệ',
		NP04: 'Thẻ thụ hưởng đang bị khóa',
		NP05: 'Giao dịch lỗi. Vui lòng thực hiện lại giao dịch',
		NP14: 'Tài khoản thụ hưởng hoặc thẻ thụ hưởng không tồn tại.',
		NP16: 'Số dư tài khoản không đủ',
		NP30: 'Giao dịch đã được gửi đến Ngân hàng thụ hưởng. Trường hợp người nhận chưa nhận được tiền, đề nghị bạn không thực hiện lại giao dịch và vui lòng liên hệ với Ngân hàng để kiểm tra',
		NP32: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		NP34: 'Thẻ thụ hưởng đang bị khóa',
		NP41: 'Thẻ thụ hưởng đang bị khóa',
		NP43: 'Thẻ thụ hưởng đang bị khóa',
		NP51: 'Giao dịch chưa thành công. Tài khoản của bạn chưa đủ số dư để thực hiện giao dịch',
		NP54: 'Thẻ thụ hưởng đã hết hạn sử sụng',
		NP68: 'Giao dịch đã được gửi đến Ngân hàng thụ hưởng. Trường hợp người nhận chưa nhận được tiền, đề nghị bạn không thực hiện lại giao dịch và vui lòng liên hệ với Ngân hàng để kiểm tra',
		NP69: 'Ngân hàng thụ hưởng đang tạm thời gián đoạn dịch vụ chuyển tiền, vui lòng thử lại sau.',
		NP76: 'Tài khoản thụ hưởng hoặc tài khoản của thẻ thụ hưởng không hợp lệ',
		NP91: 'Giao dịch không thực hiện được do ngân hàng thụ hưởng chưa tham gia dịch vụ',
		NP96: 'Giao dịch đã được gửi đến Ngân hàng thụ hưởng. Trường hợp người nhận chưa nhận được tiền, đề nghị bạn không thực hiện lại giao dịch và vui lòng liên hệ với Ngân hàng để kiểm tra',
		NP97: 'Giao dịch lỗi. Bạn vui lòng thực hiện lại giao dịch',
		TMS18237: 'Mã xác thực không chính xác, bạn vui lòng thử lại',
		VIN999:
			'Số điện thoại/CMTND không đúng với đăng ký trên hệ thống VINID. Bạn vui lòng liên hệ MB247 1900545426 để được trợ giúp hoặc đến điểm giao dịch Vingroup để xác nhận lại thông tin',
		W04: 'Thẻ đang bị khóa tạm thời',
		W14: 'Thẻ không được phép thực hiện giao dịch này',
		W32: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch ',
		W33: 'Thẻ đang bị khóa tạm thời',
		W35: 'Thẻ đang bị khóa tạm thời',
		W36: 'Thẻ đang bị khóa tạm thời',
		W37: 'Thẻ đang bị khóa tạm thời',
		W38: 'Thẻ đang bị khóa tạm thời',
		W41: 'Thẻ đang bị khóa tạm thời',
		W43: 'Thẻ đang bị khóa tạm thời',
		W51: 'Thẻ không đủ tiền để thực hiện giao dịch',
		W54: 'Thẻ chưa được kích hoạt',
		W57: 'Thẻ không được phép thực hiện giao dịch này',
		W61: 'Vượt quá hạn mức giao dịch trong ngày',
		W65: 'Vượt quá tần suất giao dịch trong ngày',
		W80: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W81: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W82: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W83: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W84: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W91: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		W96: 'Hệ thống tạm thời gián đoạn, bạn vui lòng thực hiện lại giao dịch',
		MC010: 'Sổ tiết kiệm không đảm bảo cho hạn mức thấu chi',
		MC402: 'Mã khách hàng không tồn tại, vui lòng kiểm tra lại',
		MC4083: 'Đã hết thời gian giao dịch trong ngày',
		MC4: 'Giao dịch thất bại. Vui lòng liên hệ hotline 1900545426 để biết thêm chi tiết.',
		MC209: 'Giao dịch thất bại. Vui lòng liên hệ hotline 1900545426 để biết thêm chi tiết.',
		MC4094: 'Mã khách hàng không còn nợ cước.',
		MC4093: 'Hóa đơn đã được thanh toán hết nợ cước',
		MC484: 'Trường học chưa thực hiện kết nối dịch vụ với MB.',
		MC203: 'Thông tin không hợp lệ, bạn vui lòng kiểm tra lại',
		MC4032: 'Giao dịch vấn tin không thành công',
		duration_of_insurance: 'Thời hạn bảo hiểm',
		register_consultant: 'Đăng ký tư vấn',
		buy_insurance: 'Mua bảo hiểm',
		MC007: 'Số giấy tờ tùy thân không chính xác',
		MC009: 'Quý khách không đủ điều kiện vay do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		MC014: 'Tài khoản của bạn không đủ số dư để thực hiện giao dịch',
		MC018: 'Quý khách không đủ điều kiện vay do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		MC056: 'Bạn không thể tất toán khoản vay cùng ngày mở khoản vay. Xin cảm ơn',
		'007': 'Mã hợp đồng không tồn tại.',
		MC070: 'Tài khoản của bạn không đủ số dư để thực hiện giao dịch này',
		MC090: 'Tiền gửi tiết kiệm số còn lại không đảm bảo cho HTMC',
		MC099: 'Tiền gửi tiết kiệm số còn lại không đảm bảo cho HMTC tối thiểu.',
		MC026: 'Tiền gửi tiết kiệm số còn lại không đảm bảo cho HTMC',
		MC101: 'Giao dịch đang được xử lý. Vui lòng không tiếp tục thực hiện.',
		MC400: 'Giao dịch vấn tin không thành công',
		MC231: 'Tài khoản thụ hưởng hoặc thẻ thụ hưởng không tồn tại.',
		MC4007: 'Tài khoản của khách hàng không đủ số dư để thực hiện thu phí',
		MC408: 'Giao dịch vấn tin không thành công',
		MC501: 'Giao dịch vấn tin không thành công',
		MC002: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		MC500: 'Giao dịch không thành công. Bạn vui lòng liên hệ 1900545426 để biết thêm chi tiết',
		MC301: 'Giao dịch chuyển khoản không thành công do ngân hàng thụ hưởng từ chối. Bạn vui lòng liên hệ 1900545426 để biết thêm chi tiết',
		MC201: 'Tài khoản hoặc thẻ thụ hưởng không tồn tại',
		MC4003: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		MC246: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		MC416:
			'Tài khoản nhận giải ngân không hợp lệ, Quý khách vui lòng liên hệ hotline của Mcredit 1900636769 hoặc đến trực tiếp các quầy giao dịch của MB để được hỗ trợ',
		MC4002: 'Mã nhận tiền không chính xác, quý khách vui lòng liên hệ hotline của Mcredit  1900636769 để được hỗ trợ',
		MC421: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		GW518: 'Tạm thời Thẻ chưa hỗ trợ thanh toán dịch vụ. QK vui lòng chọn nguồn là tài khoản thanh toán để thực hiện GD',
		GW526: 'Bạn vui lòng đăng ký phương thức Digital OTP để xác thực giao dịch.',
		MC211: 'Giao dịch không thành công. Vui lòng thực hiện lại giao dịch',
		MC244: 'Giao dịch không thành công. Vui lòng thực hiện lại giao dịch',
		LO01: 'Quý khách chưa đáp ứng điều kiện vay tiêu dùng theo quy định sản phẩm. Trân trọng cảm ơn!',
		LO02: 'Bạn không đủ điều kiện vay vì đang có nợ quá hạn tại MB',
		LO03: 'Giao dich vay vốn của quý khách chưa thành công do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		LO04: 'Bạn vui lòng đến điểm giao dịch gần nhất của MB để thực hiện cập nhật đăng ký dịch vụ MB điện tử theo mẫu biểu mới. Trân trọng cảm ơn!',
		LO05: 'Quý khách chưa đáp ứng điều kiện vay tiêu dùng theo quy định sản phẩm. Trân trọng cảm ơn!',
		LO15: 'Hệ thống đang xử lý giao dịch cuối ngày, bạn vui lòng thực hiện lại sau. Trân trọng cảm ơn!',
		LO20: 'Bạn không thuộc đối tượng cấp tín dụng tại MB. Trân trọng!',
		LO22: 'Quý khách không đủ điều kiện vay do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		LO022: 'Quý khách không đủ điều kiện vay do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		LO023: 'Quý khách không đủ điều kiện vay do chưa đảm bảo yêu cầu về thông tin tín dụng. Trân trọng cảm ơn!',
		LO25: 'Hôm nay là ngày thu nợ tự động khoản vay của bạn. Bạn có thể chuyển tiền vào tài khoản lựa chọn thu nợ cho khoản vay để MB tự động thu nợ hoặc thực hiện trả nợ toàn phần trên App MBBank. Trân trọng!',
		LO26: 'Bạn không thể tất toán cùng ngày mở khoản vay. Xin cảm ơn',
		MC4005: 'Lấy thông tin mã khách hàng tại nhà cung cấp bị gián đoạn. Quý khách vui lòng thực hiện lại sau',
		MC4021: 'Giao dịch không thành công do nhà cung cấp từ chối',
		MC202: 'Loại tiền tệ không hợp lệ',
		MC4051: 'Hóa đơn không hợp lệ do hóa đơn đã được thanh toán hoặc đã hết hạn thanh toán',
		MC407: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		MC219: 'Số điện thoại không tồn tại',
		MC4037: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		MC406: 'Giao dịch chưa hoàn tất. Quý khách vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết nếu tài khoản đã bị trừ tiền',
		MC411: 'Giao dịch quá hạn mức',
		MC205: 'Hệ thống tạm thời bị gián đoạn. Bạn vui lòng liên hệ tới hotline 1900545426 để được hỗ trợ.',
		MC404: 'Giao dịch không thành công. Bạn vui lòng liên hệ MB 24/7 theo số 1900545426 để biết thêm chi tiết.',
		MC232: 'Số thẻ thụ hưởng hết hạn',
		MC233: 'Số thẻ thụ hưởng hiện đang bị khóa',
		MMS01: 'QR Code không hợp lệ',
		MMS03: 'Ngân hàng thụ hưởng không hợp lệ',
		MMS04: 'Số điện thoại không hợp lệ',
		MMS05: 'Gửi thông tin sang hệ thống cửa hàng bán lẻ không thành công',
		MMS06: 'Dữ liệu không hợp lệ',
		MMS07: 'Cửa hàng bán lẻ không tồn tại',
		MMS08: 'Giao dịch thanh toán chưa nhận được kết quả trả về. Quý khách vui lòng kiểm tra số dư tài khoản trước khi thực hiện lại.',
		MMS11: 'Cửa hàng bán lẻ không hoạt động',
		MMS12: 'Số tiền thanh toán không hợp lệ',
		MMS14: 'Giao dịch thanh toán thất bại',
		MMS16: 'Số tiền không hợp lệ',
		MMS18: 'Dữ liệu không hợp lệ',
		MMS23: 'Giao dịch bị trùng',
		MMS25: 'Dữ liệu không hợp lệ',
		MMS24: 'Cửa hàng bán lẻ không hoạt động',
		MMS26: 'Không đủ hàng trong kho',
		MMS27: 'Đã hết toàn bộ hàng trong kho',
		MMS28: 'Giao dịch thanh toán đang được xử lý',
		MMS29: 'Qrcode đang tạm khoá',
		MMS96: 'Hệ thống đang bảo trì',
		MMS99: 'Lỗi hệ thống',
		MMS71: 'Điểm bán lẻ không đồng ý thực hiện giao dịch',
		MMS88: 'Giao dịch thanh toán chưa nhận được kết quả trả về. Quý khách vui lòng kiểm tra số dư tài khoản trước khi thực hiện lại.',
		MMS89: 'Số tiền không hợp lệ',
		'019': 'CIC không hợp lệ',
		'055': 'KH đang chờ check thông tin CIC ',
		'0201': 'Hệ thống đang xử lý giao dịch cuối ngày, bạn vui lòng thực hiện lại sau. Trân trọng cảm ơn!',
		MC4211: 'InterestRate not found',
		MC4202: 'Không tìm thấy thông tin khoản vay',
		MC2204: 'Không tìm thấy loại hình vay ',
		MC4204: 'Loại hình vay không hỗ trợ ',
		'057': 'Không có thông tin CIC',
		MC4242: 'Quý khách xin vui lòng không thực hiện tất toán tại ngày mở tài khoản. Trân trọng',
		MC4201: 'Result not null',
		MC2206: 'Số tiền trong tài khoản không đủ để trả phí',
		MC5201: 'System busy',
		MC4241: 'Tài khoản bị lỗi vui lòng liên hệ với bộ phận hỗ trợ để được xử lý',
		MC4240: 'Tài khoản bị lỗi(chặn). Vui lòng liên hệ với bộ phận hỗ trợ để được xử lý',
		MC2203: 'Thời gian vay không hợp lệ. Trân trọng',
		MC2202: 'Thông tin giấy tờ tùy thân của quý khách không hợp lệ. Vui lòng liên hệ MB 247 để được hỗ trợ',
		MC2205: 'Vui lòng nhập đúng thông tin tài khoản của bạn. Trân trọng',
		MC200: 'Mã khách hàng không hợp lệ',
		'037': 'KH không thuộc đối tượng cấp tín dụng tại MB',
		MC2300: 'Số tiền trong tài khoản không đủ để thực hiện thao tác này',
		MC2301: 'Hạn mức không hợp lệ',
		MC2302: 'Hạn mức vay không hợp lệ',
		MC2303: 'Số điểm của quý khách chưa đủ điều kiện vay theo quy định sản phẩm',
		MC2309: 'Danh sách tài sản đảm bảo không hợp lệ',
		MC2314: 'Sổ tiết kiệm không hợp lệ',
		MC4300: 'Tần suất tính gốc không hợp lệ ',
		MC4301: 'Tần suất nhập gốc không hợp lệ',
		MC4302: 'Lịch trả gốc hoặc lịch trả lãi phải là cuối kỳ khi ',
		MC4303: 'Không tìm thấy thông tin truy vấn ',
		MC4304: 'prSchedule or inSchedule is DINH.KY then defileSchudule is not N',
		MC4305: 'Only accept the values CCCD,CMND,CMTQD',
		MC4306: 'prSchedule or inSchedule is CUOI.KY then defileSchudule is not N',
		MC4341: 'Danh sách tài khoản tiết kiệm không hợp lê ',
		MC4342: 'Tham số nhập gốc không tìm thấy ',
		MC2330: 'Số tiền phải lớn hơn 0',
		MC2315: 'Hạn mức tăng phải lớn hơn min hạn mức sản phẩm',
		MC2316: 'Hạn mức được cấp tăng lớn hơn max hạn mức được cấp',
		MC2317: 'Hạn mức được cấp tăng lớn hơn max hạn mức sản phẩm',
		MC2318: 'Hạn mức giảm không hợp lệ',
		MC2319: 'Số tiền giảm phải lớn hơn dư nợ hiện tại.',
		MC2320: 'Đã thu PD không thực hiện revert ft',
		MC2321:
			'Tiền gửi tiết kiệm số còn lại cần đảm bảo duy trì hạn mức thấu chi tối thiểu là 5 triệu đồng và tiền lãi phát sinh của khoản vay. Vui lòng lựa chọn lại!',
		MC2322: 'Không có phí và dư nợ cần thanh toán',
		MC2323: 'Số tiền thanh toán không đúng',
		MC2324: 'Số tiền thanh toán lớn hơn số tiền cần thanh toán',
		MC2325: 'Tài khoản thấu chi đã đóng',
		MC2331: 'Khách hàng không thể giảm hạn mức ',
		MC2326: 'Vui lòng nhập đúng thông tin tài khoản thanh toán của bạn. Trân trọng',
		MC2327: 'Không tìm thấy mã chi nhánh ',
		MC2328: 'Số sổ cầm cố đã đạt tối đa',
		MC4206: 'Tần xuất lịch không hợp lệ ',
		MC4207: 'Loại lịch không hợp lê ',
		MC4223: 'Không tìm thấy loại hình lãi suất ',
		MC4224: 'Không tìm thấy chi nhánh khách hàng',
		MC4225: 'Loại tiền không hợp lệ ',
		MC4227: 'Không tìm thấy thông tin tài khoản nhận tiền',
		MC4228: 'Loại tài khoản phải là giá trị IN hoặc OUT',
		MC4229: 'Mã ngân hàng không hợp lệ ',
		MC4230: 'Tên chủ tài khoản giải ngân phải khác tên bạn. Vui lòng nhập lại',
		MC4231: 'Không tìm thấy khoản vay trên hệ thống t24',
		MC4232: 'Mã phí không tồn tại trên T24',
		MC4233: 'Tài khoản không tồn tại trên T24',
		MC4234: 'Số tiền trong tài khoản không đủ. Trân trọng',
		MC4235: 'Proposing customers to select the settlement to finalize the loan.',
		MC4236: 'Số tiền thanh toán vượt quá tổng dư nợ của khách hàng ',
		MC2208: 'Tài khoản thu phí phải tồn tại ',
		MC4237: 'Số tiền thanh toán không hợp lệ, vui lòng thanh toán toàn bộ số tiền cả gốc và lãi ',
		MC4239: 'Phương thức thanh toán nợ không phù hợp với loại hình trả nợ của khoản vay ',
		MC2209: 'Số tiền đề nghị vay không hợp lệ. Vui lòng nhập lại',
		MC2211: 'Quý khách vui lòng chọn tài khoản là tài khoản thanh toán. Trân trọng',
		MC4243: 'Số tiền thanh toán vượt quá dư nợ khoản vay ',
		MC4343: 'Quý khách xin vui lòng không thực hiện thay đổi hạn mức vào ngày hết hạn khoản vay. Trân trọng ',
		GW553: 'Không tìm thấy thông tin của khách hàng',
		GW554: 'Số điện thoại không đúng với hồ sơ đăng ký',
		GW566: 'Khánh hàng chưa được định danh bên Dform',
		MC4245: 'Giao dịch chưa thành công, nhưng đã thu nợ PD',
		GW570: 'Thuê bao đã đăng ký thanh toán tự động.',
		'-9000': 'Lỗi ngoại lệ services',
		'-9999': 'Lỗi ngoại lệ, lỗi khác',
		'-1': 'Hệ thống đã bị khóa',
		'-2': 'Loại KH không hợp lệ',
		'-3': 'Khách hàng đã tồn tại',
		'-4': 'Tài khoản đã tồn tại',
		'-5': 'Tài khoản không hợp lệ',
		'-6': 'Dải số tài khoản được cấp đã hết',
		'-7': 'Tài khoản không thể cập nhật',
		'-8': 'Lỗi nghiệp vụ khi cập nhật dữ liệu',
		'-9': 'Số TK đã được sử dụng',
		'-10': 'Người dùng không thể thực hiện cập nhật',
		'-11': 'Khách hàng không tồn tại',
		'-12': 'Tài khoản không tồn tại',
		'-13': 'Tài khoản hoặc số điện thoại đã tồn tại liên kết',
		'-14': 'Mật khẩu đăng nhập không đúng',
		'-15': 'Liên kết tài khoản đã bị hủy hoặc không tồn tại liên kết',
		'-16': 'Kích hoạt sự kiện không thành công',
		'-17': 'Tài khoản đã liên kết với một số điện thoại khác',
		'-18': 'Số điện thoại đã liên kết với một tài khoản khác',
		'-19': 'Loại giấy tờ không hợp lệ',
		'-20': 'Loại giấy tờ không cho phép ở kênh này',
		'-21': 'Kênh nhập không hợp lệ',
		'-22': 'Tài khoản tạm khóa',
		'-23': 'Tài khoản đã đóng',
		'-24': 'Không tìm thấy số tham chiếu này',
		'-25': 'Ngoài giờ giao dịch',
		'-26': 'Giá trị chuyển khoản sang MBS nhỏ hơn giá trị tối thiểu',
		'-27': 'Giá trị chuyển khoản sang MBS lớn hơn giá trị tối đa',
		'-28': 'Quý khách chưa đủ 18 tuổi để mở TKCK',
		MC419: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		MCREDIT500: 'Giao dịch chưa hoàn tất. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		MCREDIT402: 'Giao dịch không thành công. Bạn vui lòng liên hệ MB 24/7 theo số 1900 545426 để biết thêm chi tiết.',
		MCREDIT4201:
			'CMND/CCCD của quý khách đã hết hạn, vui lòng thay thế bằng giấy tờ tùy thân hợp lệ khác. Chi tiết vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ. Trân trọng cảm ơn!',
		MCREDIT4202:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900636769. Trân trọng cảm ơn!',
		MCREDIT4203:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT247: 'CMND/CCCD không hợp lệ. Chi tiết vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ. Trân trọng cảm ơn!',
		MCREDIT4204:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4205:
			'Quý khách chưa đủ thời gian đăng ký khoản vay mới tại Mcredit. Vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thêm thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT433:
			'Hiện tại, CMND/CCCD của KH đã tồn tại trên hệ thống của Mcredit.Chi tiết vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ. Trân trọng cảm ơn!',
		MCREDIT4206:
			'Quý khách chưa đủ thời gian đăng ký khoản vay mới tại Mcredit. Vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thêm thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4207:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4208:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4209:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4210:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900 63 67 69. Trân trọng cảm ơn!',
		MCREDIT204:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900 63 67 69. Trân trọng cảm ơn!',
		MCREDIT301:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT2011:
			'Quý khách đang sử dụng dịch vụ tại MB bằng Hộ chiếu/ CMT Quân đội. Vui lòng mang theo Chứng minh nhân dân/Căn cước công dân kèm Hộ chiếu/ CMT Quân đội của Quý khách ra quầy MB gần nhất để cập nhật thông tin và tiếp tục sử dụng sản phẩm dịch vụ tại Mcredit. Trân trọng cảm ơn!',
		MCREDIT4214:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900 63 67 69. Trân trọng cảm ơn!',
		MCREDIT4215:
			'Hiện tại Mcredit chưa thể hỗ trợ khoản vay cho Quý khách. Quý khách vui lòng liên hệ hotline 1900 63 67 69 để được hỗ trợ thông tin chi tiết. Trân trọng cảm ơn!',
		MCREDIT4216:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900 63 67 69. Trân trọng cảm ơn!',
		MCREDIT4221:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900636769. Trân trọng cảm ơn!',
		MCREDIT4218:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900636769. Trân trọng cảm ơn!',
		MCREDIT4219:
			'Hiện tại, CMND/CCCD của KH đã tồn tại trên hệ thống của Mcredit. Chi tiết vui lòng liên hệ hotline 1900636769 để được hỗ trợ. Trân trọng cảm ơn!',
		MCREDIT4222:
			'Hiện tại chúng tôi chưa thể cung cấp khoản vay nhanh cho Quý khách. Mcredit sẽ liên hệ với bạn sau để tư vấn khoản vay phù hợp. Thông tin chi tiết vui lòng liên hệ hotline 1900636769. Trân trọng cảm ơn!',
		GW564: 'Liên kết thiết bị đang bị khóa, Vui lòng mở liên kết để thực hiện giao dịch',
		GW542:
			'Số điện thoại đang giao dịch được gắn với nhiều khách hàng tại MB. Quý khách vui lòng liên hệ với người thụ hưởng để giao dịch chính xác và an toàn!',
	},
	http: {
		0: 'Đường truyền Internet không ổn định. Quý khách vui lòng kiểm tra lại.',
		300: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		301: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		302: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		303: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		304: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		305: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		400: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		401: 'Phiên giao dịch không hợp lệ. Vui lòng đăng nhập lại.',
		402: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		403: 'Bạn không có quyền truy cập vào dịch vụ. Vui lòng liên hệ MB 247 để được hỗ trợ',
		404: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		405: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		406: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		407: 'Tin hiệu internet không ổn định hoặc có thể bạn đang sử dụng máy chủ trung gian để sử dụng internet. Quý khách vui lòng kiểm tra lại internet và cấu hình mạng của thiết bị.',
		408: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		409: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		410: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		411: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		412: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		413: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		414: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		415: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		416: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		417: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		421: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		422: 'Bản tin không hợp lệ. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		429: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		431: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		500: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		501: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		502: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		503: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		504: 'Máy chủ không phản hồi. Vui lòng thử lại sau hoặc liên hệ MB 247 để được hỗ trợ.',
		505: 'Dịch vụ bạn sử dụng không chính xác. Vui lòng liên hệ MB 247 để được hỗ trợ.',
		511: 'Bạn không có quyền truy cập vào dịch vụ. Vui lòng liên hệ MB 247 để được hỗ trợ',
		GW600: 'Khóa bí mật reCAPTCHA không được null hoặc rỗng.',
		GW601: 'Khóa bí mật reCAPTCHA không hợp lệ hoặc không đúng định dạng.',
		GW602: 'reCAPTCHA không được null hoặc rỗng.',
		GW603: 'reCAPTCHA không hợp lệ hoặc không đúng định dạng.',
		GW604: 'Định dạng dữ liệu không hợp lệ.',
		GW605: 'reCAPTCHA đã hết hạn hoặc đã được sử dụng',
		GW606: 'Không thể verify reCAPTCHA',
	},
}

const randomString = (length) => {
	var result = ''
	var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
	var charactersLength = characters.length
	for (var i = 0; i < length; i++) {
		result += characters.charAt(Math.floor(Math.random() * charactersLength))
	}
	return result
}

const refNo = () => dayjs().format('YYYYMMDDHHmmssSSS').substr(0, 16)



function isObject(obj) {
	return obj !== undefined && obj !== null && obj.constructor == Object
}


const isJson = (str) => {
	if (!str)
		newError({
			message: 'Server MBBank đang lỗi dữ liệu, vui lòng thử lại sau.',
			status: 400,
		})

	if (isObject(str)) {
		return str
	} else {
		try {
			return JSON.parse(str)
		} catch (e) {
			return str
		}
	}
}

const postAxios = async (url, data, headers) => {
	let response = await axios.post(url, data, {
		headers: {
			...headers,
			'Content-Type': 'application/json',
			Authorization: 'Basic QURNSU46QURNSU4=',
		},
		validateStatus: () => true,
		timeout: 5000,
	})

	if (response.status != 200) {
		let error = new Error({
			url,
			data: response.data,
			status: response.status,
		})
		await error.save()
		newError({
			message: statusError.http[response.status] || response.data,
			status: 400,
		})
	}
	if (!response.data.result.ok) {
		if (headers._id && response.data.result.responseCode == 'GW200') {
			await Bank.findByIdAndUpdate(headers._id, {
				newLogin: true,
			})
		}

		newError({
			message: statusError.api[response.data.result.responseCode] || response.data.result.message,
			status: 400,
		})
	}

	let responseDecrypt = isJson(response.data)
	if (headers._id && responseDecrypt.result.responseCode == 'GW200') {
		await Bank.findByIdAndUpdate(headers._id, {
			newLogin: true,
		})
	}

	return responseDecrypt
}

const Login = async (req, res, next) => {
	let { username, _id } = req.bank
	let { password } = req.value.body
	let { irefNo, imei, resultCaptcha } = await captcha()
	let data = {
		refNo: `${username}-${irefNo}`,
		userId: username,
		password: md5(password),
		captcha: resultCaptcha,
		sessionId: null,
		deviceIdCommon: imei,
	}

	let response = await postAxios('https://online.mbbank.com.vn/retail_web/internetbanking/doLogin', data, {
		_id: false,
	})

	let sessionId = response.sessionId

	await Bank.findByIdAndUpdate(_id, {
		sessionId,
		accountNumber: Object.keys(response.cust.acct_list)[0],
		imei,
		newLogin: false,
	})
	req.bank.imei = imei
	req.bank.sessionId = sessionId
	req.bank.newLogin = false
}

const GET_BALANCE = async (req, res, next) => {
	let { username, newLogin, _id } = req.bank
	if (newLogin) await Login(req, res, next)
	let data = {
		sessionId: req.bank.sessionId,
		refNo: `${username}-${refNo()}`,
		deviceIdCommon: req.bank.imei,
	}

	let response = await postAxios('https://online.mbbank.com.vn/retail-web-accountms/getBalance', data, {
		_id,
	})

	return res.status(200).json({
		success: true,
		message: 'Thành công',
		data: response.acct_list,
	})
}

const GET_TRANSACTION = async (req, res, next) => {
	let { accountNumber } = req.value.body
	let { username, newLogin, _id, accountNumber: accountNumberDefault } = req.bank

	if (newLogin) await Login(req, res, next)

	let dayNow = new Date()
	let toDate = dayjs(dayNow).format('DD/MM/YYYY')
	let fromDate = dayjs(dayNow.setDate(dayNow.getDate() - 3)).format('DD/MM/YYYY')
	let data = {
		accountNo: accountNumber || accountNumberDefault,
		fromDate,
		toDate,
		historyNumber: '',
		historyType: 'DATE_RANGE',
		type: 'ACCOUNT',
		sessionId: req.bank.sessionId,
		refNo: `${username}-${refNo()}`,
		deviceIdCommon: req.bank.imei,
	}
	let response = await postAxios('https://online.mbbank.com.vn/retail_web/common/getTransactionHistory', data, {
		_id,
	})
	return res.status(200).json({
		success: true,
		message: 'Thành công',
		data: response.transactionHistoryList,
	})
}

const captcha = async () => {
	let irefNo = refNo()
	let imei = `${randomString(8)}-mbib-0000-0000-${irefNo}`
	let { data, status: statusCode } = await axios.post(
		'https://online.mbbank.com.vn/retail-web-internetbankingms/getCaptchaImage',
		{
			refNo: irefNo,
			deviceIdCommon: imei,
			sessionId: '',
		},
		{
			headers: {
				'Content-Type': 'application/json',
				Authorization: 'Basic QURNSU46QURNSU4=',
			},
			validateStatus: () => true,
			timeout: 1500,
		}
	)

	if (statusCode != 200) {
		newError({
			status: 400,
			message: data || 'Capcha MBBank đang gặp vấn đề, vui lòng thử lại sau.',
		})
	}
	if (!data.result.ok) {
		newError({
			status: 400,
			message: statusError.api[data.result.responseCode] || data.result.message || 'Capcha MBBank đang gặp vấn đề, vui lòng thử lại sau.',
		})
	}

	let { data: resultCaptcha } = await axios.post('http://103.154.100.194:5000/mbb', data.imageString, {
		validateStatus: () => true,
		timeout: 2000,
	})
	resultCaptcha = `${resultCaptcha}`
	if (resultCaptcha.length != 6)
		newError({
			message: 'Server Captcha đang có vấn đề vui lòng thử lại sau.',
			status: 500,
		})

	return { irefNo, imei, resultCaptcha }
}

module.exports = {
	Login,
	GET_BALANCE,
	GET_TRANSACTION,
}
